name: Deploy Backend to EC2 with Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Step 3: Initialize Terraform
      - name: Terraform Init
        working-directory: backend/terraform
        run: terraform init

      # Step 4: Apply Terraform to create EC2 instance
      - name: Terraform Apply
        working-directory: backend/terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform apply -auto-approve

      # Step 5: Fetch EC2 Public IP
      - name: Get EC2 Public IP
        id: ec2_ip
        working-directory: backend/terraform
        run: echo "::set-output name=public_ip::$(terraform output -raw ec2_public_ip)"

      # Step 6: Deploy Backend to EC2
      - name: Deploy Backend to EC2
        env:
          EC2_PUBLIC_IP: ${{ steps.ec2_ip.outputs.public_ip }}
          SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "Deploying to EC2 instance at $EC2_PUBLIC_IP..."
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          scp -o StrictHostKeyChecking=no backend.tar ec2-user@$EC2_PUBLIC_IP:/home/ec2-user/
          ssh -o StrictHostKeyChecking=no ec2-user@$EC2_PUBLIC_IP << EOF
            echo "Loading Docker image on EC2 instance..."
            docker load -i /home/ec2-user/backend.tar
            echo "Stopping existing container (if any)..."
            docker stop pinterest-clone-backend || true
            docker rm pinterest-clone-backend || true
            echo "Starting new container..."
            docker run -d --name pinterest-clone-backend -p 3000:3000 pinterest-clone-backend:latest
            echo "Deployment complete. Application is running on port 3000."
          EOF