name: Deploy Backend to EC2 with Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Step 2.1: Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      # Step 3: Initialize Terraform
      - name: Terraform Init
        working-directory: backend/terraform
        run: terraform init

      # Step 4: Apply Terraform to create EC2 instance
      - name: Terraform Apply
        working-directory: backend/terraform
        run: terraform apply -auto-approve

      # Step 5: Fetch EC2 Public IP and Private Key
      - name: Get EC2 Public IP and Private Key
        id: ec2_info
        working-directory: backend/terraform
        run: |
          echo "Fetching EC2 Public IP and Private Key..."
          EC2_PUBLIC_IP=$(terraform output -raw ec2_public_ip | tr -d '\r')
          PRIVATE_KEY=$(terraform output -raw private_key | tr -d '\r')
          echo "EC2_PUBLIC_IP=$EC2_PUBLIC_IP" >> $GITHUB_ENV
          echo "$PRIVATE_KEY" > id_rsa
          chmod 600 id_rsa
        shell: bash

      # Step 6: Deploy Node.js Application to EC2
      - name: Deploy Node.js Application
        env:
          EC2_PUBLIC_IP: ${{ env.EC2_PUBLIC_IP }}
        run: |
          echo "Deploying Node.js application to EC2 instance at $EC2_PUBLIC_IP..."
          scp -i id_rsa -o StrictHostKeyChecking=no -r backend/ ec2-user@$EC2_PUBLIC_IP:/home/ec2-user/
          ssh -i id_rsa -o StrictHostKeyChecking=no ec2-user@$EC2_PUBLIC_IP << 'EOF'
            echo "Installing dependencies..."
            cd /home/ec2-user/backend
            npm install
            echo "Starting the application with PM2..."
            pm2 stop all || true
            pm2 start index.js --name pinterest-clone-backend
            pm2 save
            echo "Deployment complete. Application is running on port 3000."
          EOF